# springBoot应用名称
spring:
  application:
    name: user-center
# DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/universe?useSSL=false
    username: root
    password: 123456

# springBoot端口号
server:
  port: 8080
  reactive:
# session超时时间
    session:
      timeout: 86400
# 指定全局接口访问路径
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
